# -*- coding: UTF-8 -*-

import os

from knewriter import KneWriter

__all__ = ['KneFileWriter']

class KneFileWriter(KneWriter):
    'Writes the data generated by the KneReader to the file system'
    
    def new_data_fp(self, nr):
        new_ed_filename = os.path.join(self.dir, "ED%05d" % (nr+1))
        return file(new_ed_filename, "wb")
    
    
    def __init__(self, config=None, dir=None):
        self.dir = dir
        
        ev_filename = os.path.join(self.dir, "EV01")
        header_fp = file(ev_filename, "wb")
        super(KneFileWriter, self).__init__(config=config, header_fp=header_fp,
                                            data_fp_builder=self.new_data_fp)

